name: Build autoremove-torrents Image
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - cron.push
      - config.example.yml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@master

      -
        name: Release version
        id: release_version
        run: |
          sudo -E timedatectl set-timezone Asia/Shanghai
          echo "app_version=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/autoremove-torrents:latest
            ${{ secrets.DOCKER_USERNAME }}/autoremove-torrents:${{ env.app_version }}